# Builds desktop\build\Underline.exe with the C# compiler that ships with Windows.
# The web app URL and secret come from ..\config.js (the same file the Chrome extension uses),
# so they never end up in git.

$ErrorActionPreference = "Stop"
$here = $PSScriptRoot
$root = Split-Path -Parent $here
$out = Join-Path $here "build"

$configPath = Join-Path $root "config.js"
if (-not (Test-Path $configPath)) { throw "config.js not found. Copy config.example.js to config.js and fill it in first." }
$config = Get-Content -Raw $configPath
$endpoint = [regex]::Match($config, 'endpoint:\s*"([^"]+)"').Groups[1].Value
$secret = [regex]::Match($config, 'secret:\s*"([^"]+)"').Groups[1].Value
if (-not $endpoint -or $endpoint -like "*PASTE*" -or -not $secret -or $secret -like "*PASTE*") {
  throw "Fill in endpoint and secret in config.js first."
}

New-Item -ItemType Directory -Force $out | Out-Null
$escape = { param($s) $s.Replace('\', '\\').Replace('"', '\"') }
@"
// Generated by build.ps1 from config.js. Do not commit.
namespace Underline
{
    static class Config
    {
        public const string Endpoint = "$(& $escape $endpoint)";
        public const string Secret = "$(& $escape $secret)";
    }
}
"@ | Set-Content -Encoding UTF8 (Join-Path $out "Config.cs")

$csc = Join-Path $env:WINDIR "Microsoft.NET\Framework64\v4.0.30319\csc.exe"
if (-not (Test-Path $csc)) { $csc = Join-Path $env:WINDIR "Microsoft.NET\Framework\v4.0.30319\csc.exe" }

& $csc /nologo /target:winexe /optimize+ /codepage:65001 `
  "/out:$(Join-Path $out 'Underline.exe')" `
  /r:System.Windows.Forms.dll /r:System.Drawing.dll /r:System.Web.Extensions.dll `
  (Join-Path $here "Underline.cs") (Join-Path $out "Config.cs")
if ($LASTEXITCODE -ne 0) { throw "Build failed." }

Write-Host "Built $(Join-Path $out 'Underline.exe')"
